### ISSUE TITLE
After update to Webots R2021b, the Webots example is not running anymore.

### ISSUE THREAD

**Issue by jelledouwe** [eager-dev/eager#175]
Command run:
roscore
rosrun eager_examples example.py

Output:
WARNING: '/home/jelle/eager_ws/src/eager_bridge_webots/worlds/tmp6lwkqukt.wbt': This file was created with Webots R2021a while you are using Webots R2021b. You may need to adjust urls for textures and meshes, see details in the change log of Webots R2021b.
INFO: ros: Starting controller: /usr/local/webots/projects/default/controllers/ros/ros --name=eager_controller
/usr/local/webots/projects/default/controllers/ros/ros: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory
WARNING: 'ros' controller exited with status: 127.

It seems that the ROS controller requires libboost_system1.65.1, while I have libboost-system1.71.0. I am not sure whether this is a problem with my installation or a more general problem.

**Comment by AlexanderKeijzer** [comment]
This is a Webots issue with Ubuntu 20.04. Fix has been merged already. https://github.com/cyberbotics/webots/issues/3486
